version: '3.1'
services:
  app:
    image: php:7.1-apache
    build: .
    ports:
      - 8080:80
    volumes:
      - .:/var/www
    restart: always
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: <%=props.dbPassword%>
      MYSQL_DATABASE: <%=props.dbName%>
      MYSQL_USER: <%=props.dbUser%>
    restart: always
    ports:
      - <%=props.dbPort%>:<%=props.dbPort%>
    volumes:
      - /var/lib/mysql
networks:
  default:
    driver: bridge