version: '3.1'
services:
  app:
    image: php:7.1-apache
    build: .
    ports:
      - 8080:80
    volumes:
      - .:/var/www
    restart: always
  db:
    image: oracle
    environment:
      #MYSQL_ROOT_PASSWORD: mysql
    restart: always
    ports:
      - 1521:1521
    volumes:
      - /opt/oracle/oradata
networks:
  default:
    driver: bridge