version: '3.1'
services:
  app:
    image: php:7.1-apache
    build: .
    ports:
      - 8080:80
    volumes:
      - .:/var/www
    restart: always
  db:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: <%=props.dbPassword%>
      POSTGRES_USER: <%=props.dbUser%>
      POSTGRES_DB: <%=props.dbName%>
    ports:
       - <%=props.dbPort%>:<%=props.dbPort%>
    volumes:
      - /var/lib/postgresql
    restart: always
networks:
  default:
    driver: bridge