version: '3.1'
services:
  app-zf3:
    image: php:7.1-apache
    build: .
    ports:
      - 8080:80
    volumes:
      - .:/var/www
    restart: always
  app-postgres:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
       - 5433:5432
    volumes:
      - /var/lib/postgresql
    restart: always
networks:
  default:
    driver: bridge